# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "macos_10.14"

  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.cpus = 3
    v.memory = "6000"
  end


  config.vm.synced_folder "../../", "/vagrant", type: "rsync"  # the normal sharing uses guest extensions, which don't exist for macOS and virtualbox
  config.vm.provision "shell", inline: "cd /vagrant/ci/src/; ./bootstrap.sh", privileged: false
  config.vm.provision "shell", inline: "mkdir -p /vagrant/build; chown -R vagrant /vagrant/build"
end
