# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "macos_10.12"

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
    v.gui = false
    v.cpus = 3
    v.memory = 8000
  end

  config.vm.synced_folder "../../", "/vagrant", type: "rsync"  # the normal sharing uses guest extensions, which don't exist for macOS and virtualbox
  config.vm.provision "shell", inline: "cd /vagrant/ci/src/; ./bootstrap-10.12.sh", privileged: false
  config.vm.provision "shell", inline: "mkdir -p /vagrant/build; chown -R vagrant /vagrant/build"
  config.vm.provision "shell", inline: "cd /vagrant/; ./build.py --translations-ref origin/5.1 --kicad-ref origin/5.1 --target package-kicad-nightly package-extras package-kicad-unified", privileged: false
end
